.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md, CONTRIBUTING.md, README.md, commitlint.config.cjs, scripts/write-compat-data.cjs, src/lib/components/pages/RelativeTimeFormat.svelte, src/lib/components/pages/Segmenter.svelte, src/lib/components/sidebar.svelte, src/lib/utils/load-json.ts, src/routes/+layout.svelte, src/routes/+page.svelte, src/routes/Collator/+page.server.ts, src/routes/DateTimeFormat/+page.server.ts, src/routes/ListFormat/+page.server.ts, src/routes/NumberFormat/Currency/+page.server.ts, src/routes/NumberFormat/Unit/+page.server.ts, src/routes/PluralRules/+page.server.ts, src/routes/RelativeTimeFormat/+page.server.ts, src/routes/Segmenter/+page.server.ts, static/Collator-compat-data.json, static/DateTimeFormat-compat-data.json, static/ListFormat-compat-data.json, static/NumberFormat-compat-data.json, static/PluralRules-compat-data.json, static/RelativeTimeFormat-compat-data.json, static/Segmenter-compat-data.json
* **Please check if the PR fulfills these requirements**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- Adds a mobile toggle and basic mobile menu functionality
=> Mobile toggle

src/lib/components/sidebar.svelte, src/routes/+layout.svelte, static/global.css
=> fix: slightly better responsive

src/lib/components/ui/CompatData.svelte, src/routes/+layout.svelte, static/global.css
=> fix: better layout for compat data on mobile

src/lib/components/pages/Collator.svelte, src/lib/components/pages/DateTimeFormat.svelte, src/lib/components/pages/ListFormat.svelte, src/lib/components/pages/NumberFormat.Currency.svelte, src/lib/components/pages/NumberFormat.Unit.svelte, src/lib/components/pages/PluralRules.svelte, src/lib/components/pages/RelativeTimeFormat.svelte, src/lib/components/pages/Segmenter.svelte, src/lib/components/sidebar.svelte, src/lib/components/ui/CompatData.svelte, src/lib/components/ui/HamburgerMenu.svelte, src/lib/components/ui/Header.svelte, src/lib/components/ui/Highlight.svelte, src/lib/components/ui/Main.svelte, src/lib/store/selected-locale.ts, src/lib/utils/get-locale.ts, src/routes/+layout.svelte, src/routes/Collator/+page.svelte, src/routes/DateTimeFormat/+page.svelte, src/routes/ListFormat/+page.svelte, src/routes/NumberFormat/Currency/+page.svelte, src/routes/NumberFormat/Unit/+page.svelte, src/routes/PluralRules/+page.svelte, src/routes/RelativeTimeFormat/+page.svelte, src/routes/Segmenter/+page.svelte, static/global.css
- Allow specifying URL from params: `?locale=sv` and with this solves prerendering being the same language as the final render. Small issue with sidebar navigation still left, not updating locale from store.
- Fixes some layout issues
=> Handle locale from URL Search Params

src/lib/components/sidebar.svelte, src/lib/components/ui/CompatData.svelte, src/lib/components/ui/Highlight.svelte, src/lib/routes.ts, src/lib/utils/get-locale.ts
And fix for lang not being updated when selecting new language in picker
- Fix sidebar issues :)
=> fix: better handling of sidebar routes

src/lib/components/sidebar.svelte, src/lib/components/ui/HamburgerMenu.svelte, src/lib/routes.ts, src/routes/+layout.svelte, tests/pages.spec.ts
=> Handle mobile menu

src/lib/components/sidebar.svelte, src/lib/components/ui/Grid.svelte, src/routes/+layout.svelte, src/routes/+page.svelte
=> fix: styling appearing different in prod

src/lib/components/sidebar.svelte, src/lib/routes.ts, src/routes/+page.svelte
Fix sidebar formatting and front page info
=> fix: info on index and sidebar formatting

src/lib/components/sidebar.svelte, src/lib/components/ui/HamburgerMenu.svelte, src/lib/components/ui/Header.svelte, src/lib/components/ui/Main.svelte, src/routes/+page.svelte
=> fix: menu sidebar

src/lib/components/sidebar.svelte, src/lib/playground/schemas/relativeTimeFormat.schema.ts
=> fix: undefined value and sidebar click

src/lib/components/sidebar.svelte, src/routes/+layout.svelte, src/routes/Playground/+page.svelte
=> fix: highlight syntax

package.json, playwright.config.ts, pnpm-lock.yaml, src/lib/components/ui/Select.svelte, src/lib/playground/schemas/collator.schema.ts, src/lib/playground/schemas/dateTimeFormat.schema.ts, src/lib/playground/schemas/pluralRules.schema.ts, src/lib/playground/schemas/relativeTimeFormat.schema.ts, src/lib/routes.ts, src/routes/Playground/+page.svelte, tests/pages.spec.ts, vercel.json
Adds more playwright tests for basic scenarios
=> test: update tests

.github/workflows/playwright.yml, playwright.config.ts
=> ci: add action for Playwright

.github/workflows/deploy.yml
Do not run for preview on branches
Run vercel deployment as manual action instead of integration
=> ci: run vercel in manual action

src/routes/+page.svelte, src/routes/Collator/+page.svelte, src/routes/DateTimeFormat/+page.svelte, src/routes/ListFormat/+page.svelte, src/routes/NumberFormat/Currency/+page.svelte, src/routes/NumberFormat/Unit/+page.svelte, src/routes/PluralRules/+page.svelte, src/routes/RelativeTimeFormat/+page.svelte, src/routes/Segmenter/+page.svelte
=> fix: add titles to every page

src/lib/components/pages/Collator.svelte, src/lib/components/pages/DateTimeFormat.svelte, src/lib/components/pages/ListFormat.svelte, src/lib/components/pages/NumberFormat.Currency.svelte, src/lib/components/pages/NumberFormat.Unit.svelte, src/lib/components/pages/PluralRules.svelte, src/lib/components/pages/RelativeTimeFormat.svelte, src/lib/components/pages/Segmenter.svelte, src/lib/routes.ts, src/routes/+layout.svelte, src/routes/Collator/+page.server.ts, src/routes/DateTimeFormat/+page.server.ts, src/routes/ListFormat/+page.server.ts, src/routes/NumberFormat/Currency/+page.server.ts, src/routes/NumberFormat/Unit/+page.server.ts, src/routes/Playground/+page.svelte, src/routes/PluralRules/+page.server.ts, src/routes/RelativeTimeFormat/+page.server.ts, src/routes/Segmenter/+page.server.ts, tests/pages.spec.ts
- fix: correct types on page load return
- fix: add locale select to every page
- fix: validate schema input
=> fix various issues

src/lib/playground/format.utils.ts, src/lib/playground/schemas/dateTimeFormat.schema.ts
=> fix: check if options are undefined instead of falsy

src/lib/components/pages/Collator.svelte, src/lib/components/pages/DateTimeFormat.svelte, src/lib/components/pages/ListFormat.svelte, src/lib/components/pages/NumberFormat.Currency.svelte, src/lib/components/pages/NumberFormat.Unit.svelte, src/lib/components/pages/PluralRules.svelte, src/lib/components/pages/RelativeTimeFormat.svelte, src/lib/components/pages/Segmenter.svelte, src/lib/playground/format.utils.ts, src/routes/Playground/+page.svelte
=> feat: add resolved options

src/lib/components/pages/DateTimeFormat.svelte, src/lib/components/pages/ListFormat.svelte, src/lib/components/pages/NumberFormat.Currency.svelte, src/lib/components/pages/NumberFormat.Unit.svelte, src/lib/components/ui/DateTime.svelte, src/routes/+layout.svelte, src/routes/Playground/+page.svelte, tests/pages.spec.ts
=> feat: add alternative use case and add datetime picker

src/lib/components/pages/DateTimeFormat.svelte, src/lib/components/ui/CompatData.svelte, src/lib/components/ui/Header.svelte, src/lib/components/ui/Main.svelte, src/lib/playground/schemas/dateTimeFormat.schema.ts, src/routes/+layout.svelte, src/routes/Playground/+page.svelte, tests/pages.spec.ts
=> fix: layout issues

src/lib/components/ui/CompatData.svelte, src/lib/components/ui/Header.svelte, src/lib/components/ui/MDNLink.svelte, src/lib/components/ui/SkipLink.svelte, src/lib/playground/format.utils.ts, src/lib/playground/playground.schema.ts, src/lib/playground/schemas/collator.schema.ts, src/lib/playground/schemas/dateTimeFormat.schema.ts, src/lib/playground/schemas/listFormat.schema.ts, src/lib/playground/schemas/numberFormat.schema.ts, src/lib/playground/schemas/pluralRules.schema.ts, src/lib/playground/schemas/relativeTimeFormat.schema.ts, src/lib/playground/schemas/segmenter.schema.ts, src/routes/+layout.svelte, src/routes/Playground/+page.svelte
Adds ability to view secondary formatters:
- formatToParts
- formatRange
=> feat: add support for secondary formatters

src/lib/components/sidebar.svelte, src/lib/components/ui/Main.svelte, src/lib/components/ui/ProgressBar.svelte, src/routes/+layout.svelte, src/routes/+page.svelte, src/routes/Collator/+page.svelte, src/routes/DateTimeFormat/+page.svelte, src/routes/ListFormat/+page.svelte, src/routes/NumberFormat/Currency/+page.svelte, src/routes/NumberFormat/Unit/+page.svelte, src/routes/Playground/+page.svelte, src/routes/PluralRules/+page.svelte, src/routes/RelativeTimeFormat/+page.svelte, src/routes/Segmenter/+page.svelte, tests/pages.spec.ts
also move a11y tests to separate test because they need to wait for animation
=> fix: animation on menu and navigation loading

src/lib/components/pages/DateTimeFormat.svelte, src/lib/components/pages/ListFormat.svelte, src/lib/components/pages/NumberFormat.Currency.svelte, src/lib/components/pages/NumberFormat.Unit.svelte, src/lib/components/ui/CodeBlock.svelte, src/lib/components/ui/Highlight.svelte, src/lib/components/ui/Highlight/Token.svelte, src/lib/components/ui/HighlightValue.svelte, src/routes/+layout.svelte, tests/pages.spec.ts
- fix: highlight without hljs
- feat: highlight withouth hljs
=> highlight without hljs

src/lib/components/pages/RelativeTimeFormat.svelte, src/lib/components/ui/Input.svelte, src/lib/playground/playground.schema.ts, src/lib/playground/schemas/dateTimeFormat.schema.ts, src/lib/playground/schemas/numberFormat.schema.ts, src/routes/Playground/+page.svelte
Adds basic validation and clamping for values on options that are numbers
=> fix: add validation for options (min/max)

src/app.html
=> fix: add meta description tag

src/routes/+page.svelte
* [] Tests for the changes have been added (for bug fixes / features)
* [] Docs have been added / updated (for bug fixes / features)
=> fix: broken url to Intl MDN page

src/lib/components/pages/DateTimeFormat.svelte, src/lib/components/pages/ListFormat.svelte, src/lib/components/pages/NumberFormat.Currency.svelte, src/lib/components/pages/NumberFormat.Unit.svelte, src/lib/components/ui/Highlight.svelte, src/lib/components/ui/Highlight/Token.svelte, src/lib/components/ui/HighlightValue.svelte, tests/pages.spec.ts
=> fix: minor ui and a11y fixes

src/lib/playground/schemas/dateTimeFormat.schema.ts
=> fix: add year options for DateTimeFormat

package.json, pnpm-lock.yaml, src/routes/+layout.svelte
=> fix: remove analytics

src/routes/+layout.svelte
=> feat: add analytics

src/lib/components/Sidebar.svelte, src/lib/components/pages/Collator.svelte, src/lib/components/pages/DateTimeFormat.svelte, src/lib/components/pages/DisplayNames.svelte, src/lib/components/pages/ListFormat.svelte, src/lib/components/pages/NumberFormat.Currency.svelte, src/lib/components/pages/NumberFormat.Unit.svelte, src/lib/components/pages/NumberFormat.svelte, src/lib/components/pages/Playground/PlaygroundInput.svelte, src/lib/components/pages/PluralRules.svelte, src/lib/components/pages/RelativeTimeFormat.svelte, src/lib/components/pages/Segmenter.svelte, src/lib/components/ui/ComboBox/ComboBox.svelte, src/lib/locale-data/locales.ts, src/lib/routes.ts, src/routes/+page.svelte
=> feat: add combobox

.npmrc
=> fix: pnpm version mismatch

src/lib/components/pages/Playground/Playground.svelte, src/lib/components/pages/Playground/PlaygroundOptions.svelte, src/lib/components/pages/Playground/PlaygroundSecondaryFormatters.svelte, src/lib/components/ui/CompatData.svelte
=> fix: playground browser support

src/lib/components/ui/ComboBox/ComboBox.svelte, src/lib/components/ui/DateTime.svelte, src/lib/components/ui/Input.svelte, src/lib/components/ui/Main.svelte, src/lib/components/ui/Select.svelte, src/lib/components/ui/icons/ChevronUp.svelte, src/routes/+layout.svelte
=> fix: input styling and chevrons

src/lib/components/ui/ComboBox/ComboBox.svelte, src/lib/components/ui/Input.svelte, src/lib/components/ui/Select.svelte, src/lib/components/ui/icons/ChevronUp.svelte, src/routes/+layout.svelte
=> fix: select chevron

src/routes/+page.svelte
=> fix: spacing on front page

src/routes/+layout.svelte
=> fix: readd analytics

src/app.d.ts, src/lib/components/pages/Playground/Playground.svelte, src/lib/utils/analytics.ts
=> feat: track playground events

src/app.html, src/lib/components/Sidebar.svelte, src/lib/components/pages/Collator.svelte, src/lib/components/pages/DateTimeFormat.svelte, src/lib/components/pages/ListFormat.svelte, src/lib/components/pages/NumberFormat.Currency.svelte, src/lib/components/pages/NumberFormat.Unit.svelte, src/lib/components/pages/NumberFormat.svelte, src/lib/components/pages/PluralRules.svelte, src/lib/components/pages/RelativeTimeFormat.svelte, src/lib/components/pages/Segmenter.svelte, src/lib/components/ui/MDNLink.svelte, src/lib/store/selected-locale.ts, src/lib/utils/analytics.ts, src/routes/+layout.svelte
=> fix: more analytics

src/lib/components/Sidebar.svelte, src/lib/components/pages/Collator.svelte, src/lib/components/pages/DateTimeFormat.svelte, src/lib/components/pages/DisplayNames.svelte, src/lib/components/pages/DurationFormat.svelte, src/lib/components/pages/ListFormat.svelte, src/lib/components/pages/NumberFormat.Currency.svelte, src/lib/components/pages/NumberFormat.Unit.svelte, src/lib/components/pages/NumberFormat.svelte, src/lib/components/pages/PageLayout.svelte, src/lib/components/pages/Playground/Playground.svelte, src/lib/components/pages/Playground/PlaygroundInput.svelte, src/lib/components/pages/Playground/PlaygroundOptions.svelte, src/lib/components/pages/Playground/PlaygroundSecondaryFormatters.svelte, src/lib/components/pages/PluralRules.svelte, src/lib/components/pages/RelativeTimeFormat.svelte, src/lib/components/pages/Segmenter.svelte, src/routes/Collator/+page.svelte, src/routes/DateTimeFormat/+page.svelte, src/routes/DisplayNames/+page.svelte, src/routes/DurationFormat/+page.svelte, src/routes/ListFormat/+page.svelte, src/routes/NumberFormat/+page.svelte, src/routes/NumberFormat/Currency/+page.svelte, src/routes/NumberFormat/Unit/+page.svelte, src/routes/PluralRules/+page.svelte, src/routes/RelativeTimeFormat/+page.svelte, src/routes/Segmenter/+page.svelte
=> fix: merge layouts

src/app.d.ts, src/lib/components/Sidebar.svelte, src/lib/components/pages/Collator.svelte, src/lib/components/pages/DateTimeFormat.svelte, src/lib/components/pages/DurationFormat.svelte, src/lib/components/pages/ListFormat.svelte, src/lib/components/pages/NumberFormat.Currency.svelte, src/lib/components/pages/NumberFormat.Unit.svelte, src/lib/components/pages/NumberFormat.svelte, src/lib/components/pages/Playground/Playground.svelte, src/lib/components/pages/PluralRules.svelte, src/lib/components/pages/RelativeTimeFormat.svelte, src/lib/components/pages/Segmenter.svelte, src/lib/components/ui/MDNLink.svelte, src/lib/store/selected-locale.ts, src/lib/utils/analytics.ts
=> fix: reduce tracking

package.json, pnpm-lock.yaml, src/app.d.ts, src/lib/components/ui/Select.svelte, src/lib/format-options/common.options.ts, src/lib/format-options/number-format.options.ts, src/lib/format-options/plural-rules.options.ts, src/lib/playground/format.utils.ts, src/lib/playground/schemas/numberFormat.schema.ts, src/lib/playground/schemas/pluralRules.schema.ts, src/lib/utils/format-utils.ts, src/routes/DurationFormat/+page.server.ts, src/routes/DurationFormat/+page.svelte
=> feat: add more rounding options

src/lib/components/Sidebar.svelte, src/lib/components/pages/DateTimeFormat.svelte, src/lib/components/pages/NumberFormat.Currency.svelte, src/lib/components/pages/NumberFormat.Unit.svelte, src/lib/components/pages/NumberFormat.svelte, src/lib/components/pages/Playground/PlaygroundOptions.svelte, src/lib/components/pages/PluralRules.svelte, src/lib/components/ui/ComboBox/ComboBox.svelte, src/lib/components/ui/Select.svelte, tests/IntlPage.ts, tests/contstants.ts, tests/pages.spec.ts
=> fix: try format catch and a11y fixes

src/lib/components/pages/Playground/Playground.svelte, src/lib/components/pages/Playground/PlaygroundOptions.svelte, src/lib/components/ui/OptionCard.svelte, src/lib/playground/format.utils.ts, src/lib/playground/playground.schema.ts, src/lib/playground/schemas/validate.ts
=> feat: add toggling for options

src/lib/components/pages/Collator.svelte, src/lib/components/pages/DateTimeFormat.svelte, src/lib/components/pages/DurationFormat.svelte, src/lib/components/pages/ListFormat.svelte, src/lib/components/pages/NumberFormat.Currency.svelte, src/lib/components/pages/NumberFormat.Unit.svelte, src/lib/components/pages/NumberFormat.svelte, src/lib/components/pages/PageLayout.svelte, src/lib/components/pages/Playground/Playground.svelte, src/lib/components/pages/Playground/PlaygroundInput.svelte, src/lib/components/pages/RelativeTimeFormat.svelte, src/lib/components/pages/Segmenter.svelte, src/lib/components/ui/ComboBox/ComboBox.svelte, src/lib/components/ui/DateTime.svelte, src/lib/components/ui/Grid.svelte, src/lib/components/ui/Header.svelte, src/lib/components/ui/OptionSection.svelte, src/lib/utils/format-utils.ts, static/DurationFormat-compat-data.json
=> fix: grid layouts

src/lib/components/Sidebar.svelte, src/lib/components/pages/Playground/PlaygroundOptions.svelte, src/lib/components/ui/BrowserSupport/BrowserSupportGrid.svelte, src/lib/components/ui/Button.svelte, src/lib/components/ui/Card.svelte, src/lib/components/ui/CodeBlock.svelte, src/lib/components/ui/ComboBox/ComboBox.svelte, src/lib/components/ui/CopyButton.svelte, src/lib/components/ui/HamburgerMenu.svelte, src/lib/components/ui/Main.svelte, src/lib/components/ui/OptionCard.svelte, src/lib/components/ui/SkipLink.svelte, src/lib/components/ui/details/Details.svelte, src/lib/components/ui/icons/ChevronUp.svelte, src/routes/+layout.svelte
=> feat: add basic dark mode

src/lib/components/Sidebar.svelte, src/lib/components/pages/Playground/Playground.svelte, src/lib/components/pages/Playground/PlaygroundSecondaryFormatters.svelte, src/lib/components/ui/DarkModeToggle.svelte, src/lib/components/ui/icons/Moon.svelte, src/lib/components/ui/icons/Sun.svelte, src/routes/+layout.svelte
=> feat: add dark mode toggle

src/lib/components/ui/DarkModeToggle.svelte
=> fix: dark mode toggle rendering

src/lib/components/ui/DarkModeToggle.svelte
=> fix: apply dark mode on body

src/lib/components/ui/DarkModeToggle.svelte, src/routes/+layout.svelte
=> fix: persist dark mode

src/lib/components/pages/Playground/Playground.svelte
=> fix: active toggle name change

src/lib/components/pages/Collator.svelte, src/lib/components/pages/DateTimeFormat.svelte, src/lib/components/pages/DurationFormat.svelte, src/lib/components/pages/ListFormat.svelte, src/lib/components/pages/NumberFormat.Currency.svelte, src/lib/components/pages/NumberFormat.Unit.svelte, src/lib/components/pages/NumberFormat.svelte, src/lib/components/pages/Playground/Playground.svelte, src/lib/components/pages/PluralRules.svelte, src/lib/components/pages/RelativeTimeFormat.svelte, src/lib/components/pages/Segmenter.svelte, src/lib/components/ui/Dialog.svelte, src/lib/components/ui/OptionSection.svelte
=> fix: make output reactive to lang

src/lib/components/pages/Playground/PlaygroundOptions.svelte, src/lib/components/pages/PluralRules.svelte, src/lib/components/pages/RelativeTimeFormat.svelte, src/lib/components/ui/Checkbox.svelte, src/lib/components/ui/Fieldset.svelte, src/lib/components/ui/OptionCard.svelte, src/lib/components/ui/Radio.svelte, src/lib/playground/format.utils.ts, src/lib/playground/validate.ts
=> fix: style checkboxes and radios

src/lib/components/pages/PageLayout.svelte, src/lib/components/pages/Playground/Playground.svelte, src/lib/components/pages/Playground/PlaygroundOptions.svelte, src/lib/components/ui/CodeBlock.svelte, src/lib/components/ui/DarkModeToggle.svelte, src/lib/components/ui/Dialog.svelte, src/lib/components/ui/Fieldset.svelte, src/lib/components/ui/Highlight/Token.svelte, src/lib/components/ui/Navigation.svelte, src/lib/components/ui/OptionSection.svelte, src/lib/components/ui/Radio.svelte, src/lib/components/ui/SettingsDialog.svelte, src/lib/store/settings.ts, src/lib/utils/directives.ts, src/lib/utils/format-utils.ts, src/routes/+layout.svelte, src/routes/Playground/+page.svelte
=> feat: add settings and code dark mode

src/lib/components/pages/Playground/Playground.svelte, src/lib/components/pages/Playground/PlaygroundOptions.svelte, src/lib/components/ui/BrowserSupport/BrowserSupport.svelte, src/lib/components/ui/OptionSection.svelte, src/lib/components/ui/details/Details.svelte
=> fix: mobile fixes

src/lib/components/ui/Main.svelte, src/routes/+layout.svelte
=> fix: front page

messages/en.json, src/lib/components/pages/ListFormat.svelte, src/lib/components/ui/BrowserSupport/SupportLabel.svelte, src/lib/components/ui/Button.svelte, src/lib/components/ui/Card.svelte, src/lib/components/ui/Checkbox.svelte, src/lib/components/ui/Chip.svelte, src/lib/components/ui/CodeBlock.svelte, src/lib/components/ui/ComboBox.svelte, src/lib/components/ui/Highlight/Token.svelte, src/lib/components/ui/LocalePicker.svelte, src/lib/components/ui/Navigation.svelte, src/lib/components/ui/Radio.svelte, src/lib/components/ui/SettingsDialog.svelte, src/lib/components/ui/Slider.svelte, src/lib/components/ui/details/Details.svelte, src/lib/components/ui/icons/ChevronUp.svelte, src/lib/store/settings.ts, src/routes/+layout.svelte
=> fix: color schemes

src/lib/components/ui/Input.svelte, src/lib/components/ui/Select.svelte
=> fix: spacing on inputs

src/lib/playground/format.utils.ts
=> fix: do not sort original array

src/lib/components/ui/DateTime.svelte
=> fix: adjust spacing

.github/workflows/deploy.yml
=> chore: bump pnpm version

.github/workflows/deploy.yml, .github/workflows/playwright.yml, package.json, playwright.config.ts, src/lib/components/pages/Playground/Playground.svelte, src/lib/components/ui/Button.svelte, src/lib/components/ui/Navigation.svelte, src/lib/constants.ts, src/lib/utils/dom-utils.ts, src/routes/+layout.svelte, tests/IntlPage.ts, tests/pages.spec.ts
=> chore: update tests

.github/workflows/e2e-tests.yml, .github/workflows/unit-tests.yml, messages/sv.json, playwright.config.ts, src/lib/components/ui/Navigation.svelte, src/lib/components/ui/SettingsDialog.svelte, src/lib/components/ui/Slider.svelte, src/lib/utils/dom-utils.ts, src/routes/+layout.svelte, tests/methods.spec.ts, tests/pages/BasePage.ts, tests/pages/IntlPage.ts, tests/pages/PlaygroundPage.ts, tests/pages/SettingsPage.ts, tests/playground.spec.ts, tests/settings.spec.ts, tests/test.ts
- Adds e2e tests for individual method pages
- Adds e2e tests for settings page
- Fixes some a11y issues found during testing
- Increase contrast for various parts of page
=> chore: add  more e2e tests
